# Generated by Django 4.0.6 on 2022-07-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
